app_key: "secret"
debug_mode: true

# Server configurations
server:
    host: "localhost"
    port: 8000
      
# Database credentials
database:
    connection: "postgres"
    user: "postgres"
    pass: "123"
    port: 5432
    database: "sdku"
    host: "localhost"